/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quitation;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jahed
 */
public class CreateProfile extends javax.swing.JFrame {

    /**
     * Creates new form CreateProfile
     */
    String Imagepath = null;

    public CreateProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HadingPanal = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        CreateProfileHading = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        MainPanal = new javax.swing.JPanel();
        CAdd = new javax.swing.JLabel();
        CName = new javax.swing.JLabel();
        Clogo = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        Conpass = new javax.swing.JLabel();
        CnamText = new javax.swing.JTextField();
        CaddText = new javax.swing.JTextField();
        UserNamText = new javax.swing.JTextField();
        UserPass2 = new javax.swing.JPasswordField();
        Userpass1 = new javax.swing.JPasswordField();
        picSpace = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Browse = new javax.swing.JButton();
        ShowPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HadingPanal.setBackground(new java.awt.Color(24, 33, 43));
        HadingPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 3, true));
        HadingPanal.setLayout(null);

        Q1.setBackground(new java.awt.Color(24, 33, 43));
        Q1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setText("Quotation");
        HadingPanal.add(Q1);
        Q1.setBounds(0, 0, 100, 30);

        Q2.setBackground(new java.awt.Color(24, 33, 43));
        Q2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2.setText("     Maker.");
        HadingPanal.add(Q2);
        Q2.setBounds(0, 16, 100, 30);

        CreateProfileHading.setBackground(new java.awt.Color(24, 33, 43));
        CreateProfileHading.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        CreateProfileHading.setForeground(new java.awt.Color(255, 255, 255));
        CreateProfileHading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateProfileHading.setText("Create profile");
        HadingPanal.add(CreateProfileHading);
        CreateProfileHading.setBounds(160, 4, 180, 40);

        Exit.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        HadingPanal.add(Exit);
        Exit.setBounds(450, 10, 30, 30);

        min.setBackground(new java.awt.Color(24, 33, 43));
        min.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setText("-");
        min.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        HadingPanal.add(min);
        min.setBounds(400, 10, 40, 30);

        MainPanal.setBackground(new java.awt.Color(24, 33, 43));
        MainPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 3, true));
        MainPanal.setLayout(null);

        CAdd.setBackground(new java.awt.Color(24, 33, 43));
        CAdd.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CAdd.setForeground(new java.awt.Color(255, 255, 255));
        CAdd.setText("Full addres");
        MainPanal.add(CAdd);
        CAdd.setBounds(20, 60, 140, 30);

        CName.setBackground(new java.awt.Color(24, 33, 43));
        CName.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CName.setForeground(new java.awt.Color(255, 255, 255));
        CName.setText("Compay name");
        MainPanal.add(CName);
        CName.setBounds(20, 20, 140, 30);

        Clogo.setBackground(new java.awt.Color(24, 33, 43));
        Clogo.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Clogo.setForeground(new java.awt.Color(255, 255, 255));
        Clogo.setText("Company logo");
        MainPanal.add(Clogo);
        Clogo.setBounds(20, 250, 140, 40);

        UserName.setBackground(new java.awt.Color(24, 33, 43));
        UserName.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setText("User name");
        MainPanal.add(UserName);
        UserName.setBounds(20, 100, 140, 30);

        Pass.setBackground(new java.awt.Color(24, 33, 43));
        Pass.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText("Password");
        MainPanal.add(Pass);
        Pass.setBounds(20, 140, 140, 30);

        Conpass.setBackground(new java.awt.Color(24, 33, 43));
        Conpass.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Conpass.setForeground(new java.awt.Color(255, 255, 255));
        Conpass.setText("Confirm pass");
        MainPanal.add(Conpass);
        Conpass.setBounds(20, 180, 140, 30);

        CnamText.setBackground(new java.awt.Color(44, 53, 63));
        CnamText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CnamText.setForeground(new java.awt.Color(255, 255, 255));
        CnamText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CnamText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        CnamText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnamTextActionPerformed(evt);
            }
        });
        MainPanal.add(CnamText);
        CnamText.setBounds(180, 20, 300, 30);

        CaddText.setBackground(new java.awt.Color(44, 53, 63));
        CaddText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CaddText.setForeground(new java.awt.Color(255, 255, 255));
        CaddText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CaddText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        CaddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaddTextActionPerformed(evt);
            }
        });
        MainPanal.add(CaddText);
        CaddText.setBounds(180, 60, 300, 28);

        UserNamText.setBackground(new java.awt.Color(44, 53, 63));
        UserNamText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        UserNamText.setForeground(new java.awt.Color(255, 255, 255));
        UserNamText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserNamText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        UserNamText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamTextActionPerformed(evt);
            }
        });
        MainPanal.add(UserNamText);
        UserNamText.setBounds(180, 100, 300, 28);

        UserPass2.setBackground(new java.awt.Color(44, 53, 63));
        UserPass2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        UserPass2.setForeground(new java.awt.Color(255, 255, 255));
        UserPass2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserPass2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        UserPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPass2ActionPerformed(evt);
            }
        });
        MainPanal.add(UserPass2);
        UserPass2.setBounds(180, 180, 210, 30);

        Userpass1.setBackground(new java.awt.Color(44, 53, 63));
        Userpass1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Userpass1.setForeground(new java.awt.Color(255, 255, 255));
        Userpass1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Userpass1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Userpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Userpass1ActionPerformed(evt);
            }
        });
        MainPanal.add(Userpass1);
        Userpass1.setBounds(180, 140, 210, 30);

        picSpace.setBackground(new java.awt.Color(44, 53, 63));
        picSpace.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        MainPanal.add(picSpace);
        picSpace.setBounds(180, 220, 210, 100);

        Save.setBackground(new java.awt.Color(44, 53, 63));
        Save.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.setFocusPainted(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        MainPanal.add(Save);
        Save.setBounds(200, 370, 130, 30);

        Browse.setBackground(new java.awt.Color(44, 53, 63));
        Browse.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Browse.setForeground(new java.awt.Color(255, 255, 255));
        Browse.setText("Browse");
        Browse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Browse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Browse.setFocusPainted(false);
        Browse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        MainPanal.add(Browse);
        Browse.setBounds(400, 250, 80, 30);

        ShowPass.setBackground(new java.awt.Color(44, 53, 63));
        ShowPass.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        ShowPass.setForeground(new java.awt.Color(255, 255, 255));
        ShowPass.setText("Show");
        ShowPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        MainPanal.add(ShowPass);
        ShowPass.setBounds(400, 160, 80, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanal, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addComponent(HadingPanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HadingPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setForeground(new java.awt.Color(128, 0, 0));

    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setForeground(new java.awt.Color(128, 128, 128));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void CnamTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnamTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnamTextActionPerformed

    private void CaddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaddTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaddTextActionPerformed

    private void UserNamTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamTextActionPerformed

    private void UserPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPass2ActionPerformed

    private void Userpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Userpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Userpass1ActionPerformed

    //Chack data validity
    private boolean varifydata() {
        if (CnamText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty company name field");
            return false;
        } else if (CaddText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty company address field");
            return false;
        } else if (UserNamText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty user name field");
            return false;
        } else if (Userpass1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty password field");
            return false;
        } else if (!Userpass1.getText().equals(UserPass2.getText())) {
            JOptionPane.showMessageDialog(null, "Password not matched");

            return false;
        } else if (Imagepath == null) {
            JOptionPane.showMessageDialog(null, "No image selected");
            return false;
        } else {
            return true;
        }
    }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Connection con = DBConnection.getConnection();
        PreparedStatement ps;

        if (varifydata()) {
            try {
                ps = (PreparedStatement) con.prepareStatement("UPDATE `admin` SET"
                        + "`CompanyName`=?,"
                        + "`CompanyAddress`=?,"
                        + "`UserName`=?,"
                        + "`Password`=?,"
                        + "`Logo`=? WHERE 1");
                ps.setString(1, CnamText.getText());
                ps.setString(2, CaddText.getText());
                ps.setString(3, UserNamText.getText());
                ps.setString(4, String.valueOf(UserPass2.getPassword()));
                InputStream img = new FileInputStream(new File(Imagepath));
                ps.setBlob(5, img);
                if (ps.executeUpdate() != 0) {
                    JOptionPane.showMessageDialog(null, "done update");
                    

                } else {
                    JOptionPane.showMessageDialog(null, "Something wrong");
                }
            } catch (Exception ex) {
                Logger.getLogger(ex.getMessage());
            }

        }
    }//GEN-LAST:event_SaveActionPerformed

    // Size Image
    private ImageIcon resizepic(String picpath) {
        ImageIcon myimg = new ImageIcon(picpath);
        Image img = myimg.getImage().getScaledInstance(picSpace.getWidth() - 3, picSpace.getHeight() - 3, Image.SCALE_SMOOTH);
        ImageIcon mypic = new ImageIcon(img);
        return mypic;
    }

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        JFileChooser filec = new JFileChooser();
        filec.setCurrentDirectory(new File(System.getProperty("user.home")));

        //file extention
        FileNameExtensionFilter filefilter = new FileNameExtensionFilter(".Images", "jpg", "png", "gif");
        filec.addChoosableFileFilter(filefilter);
        int filestate = filec.showSaveDialog(null);

        //if user select a file
        if (filestate == JFileChooser.APPROVE_OPTION) {
            File selectedfile = filec.getSelectedFile();
            String path = selectedfile.getAbsolutePath();
            Imagepath = path;
            // Display the image in jlavel

            picSpace.setIcon(resizepic(path));
        }
    }//GEN-LAST:event_BrowseActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        if (ShowPass.isSelected()) {
            Userpass1.setEchoChar((char) 0);
            UserPass2.setEchoChar((char) 0);
        } else {
            Userpass1.setEchoChar('*');
            UserPass2.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JLabel CAdd;
    private javax.swing.JLabel CName;
    private javax.swing.JTextField CaddText;
    private javax.swing.JLabel Clogo;
    private javax.swing.JTextField CnamText;
    private javax.swing.JLabel Conpass;
    private javax.swing.JLabel CreateProfileHading;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel HadingPanal;
    private javax.swing.JPanel MainPanal;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JButton Save;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JTextField UserNamText;
    private javax.swing.JLabel UserName;
    private javax.swing.JPasswordField UserPass2;
    private javax.swing.JPasswordField Userpass1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel picSpace;
    // End of variables declaration//GEN-END:variables
}
