/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quitation;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jahed
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee Civil Work Iron Work Wooden Work Steel Work
     * Sanetary Work Plambing Work Electrical Work Landscap Others
     */
    
    private float Quantity;
    private float price;
    private float tatalprice;
    
    private int srow;

    public Employee() {
        initComponents();
        ShowDataInproducttable();
        //ShowDataInQuotationProducttable();
    }

   
    // AllProduct list
    public ArrayList<QuotationAllProductTable> ProductList() {
        ArrayList<QuotationAllProductTable> ProductList = new ArrayList<>();
        Connection con = DBConnection.getConnection();
        String query = "SELECT * FROM `product` WHERE `Catagory` = " + "\"" + (String) ProductCatagoryOption.getSelectedItem() + "\"";

        Statement st;
        ResultSet rs;
        try {
            st = (Statement) con.createStatement();
            rs = st.executeQuery(query);
            QuotationAllProductTable productdata;
            while (rs.next()) {
                productdata = new QuotationAllProductTable(rs.getInt("id"),
                        rs.getString("Discription"),
                        rs.getString("Catagory"),
                        rs.getString("unit"),
                        rs.getFloat("price"));
                ProductList.add(productdata);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ProductList;
    }

    //Show product in table of selected catagory
    private void ShowDataInproducttable() {
        ArrayList<QuotationAllProductTable> list = ProductList();
        DefaultTableModel model = (DefaultTableModel) QuotationProductTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getId();
            row[1] = list.get(i).getDiscription();
            row[2] = list.get(i).getCatagory();
            row[3] = list.get(i).getUnit();
            row[4] = list.get(i).getPrice();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HadingPanal = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        EmployeeLogout = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        EmployeeHeading1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Billaplicationtext = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        totalAmount = new javax.swing.JLabel();
        Billno = new javax.swing.JLabel();
        companyaddress = new javax.swing.JLabel();
        companyname = new javax.swing.JLabel();
        WorkingBill = new javax.swing.JLabel();
        Advancepay = new javax.swing.JLabel();
        AcountDetail = new javax.swing.JLabel();
        BillNoText = new javax.swing.JTextField();
        AcountDetaileText = new javax.swing.JTextField();
        CompanyNameText = new javax.swing.JTextField();
        CompanyAddressText = new javax.swing.JTextField();
        WorkingBillText = new javax.swing.JTextField();
        AdvancePayText = new javax.swing.JTextField();
        BillSave = new javax.swing.JButton();
        payableAmount1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        QuotationSearchPanel1 = new javax.swing.JPanel();
        ProductCatagoryOption = new javax.swing.JComboBox<>();
        CatagoryLabale = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        QuotationProductTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        QuotationTable = new javax.swing.JTable();
        Save = new javax.swing.JButton();
        ProductDescriptionLabel2 = new javax.swing.JLabel();
        QuotationNo = new javax.swing.JTextField();
        ProductDescriptionLabel4 = new javax.swing.JLabel();
        ReciverCompanyNameText = new javax.swing.JTextField();
        ProductDescriptionLabel3 = new javax.swing.JLabel();
        RecivedrCompanyAddressText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HadingPanal.setBackground(new java.awt.Color(24, 33, 43));
        HadingPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 3, true));
        HadingPanal.setLayout(null);

        Q1.setBackground(new java.awt.Color(24, 33, 43));
        Q1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setText("Quotation");
        HadingPanal.add(Q1);
        Q1.setBounds(0, 0, 100, 30);

        Q2.setBackground(new java.awt.Color(24, 33, 43));
        Q2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2.setText("     Maker.");
        HadingPanal.add(Q2);
        Q2.setBounds(0, 16, 100, 30);

        EmployeeLogout.setBackground(new java.awt.Color(24, 33, 43));
        EmployeeLogout.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        EmployeeLogout.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeLogout.setText("Logout");
        EmployeeLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        EmployeeLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseExited(evt);
            }
        });
        HadingPanal.add(EmployeeLogout);
        EmployeeLogout.setBounds(880, 10, 80, 30);

        Exit.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        HadingPanal.add(Exit);
        Exit.setBounds(1020, 10, 30, 30);

        min.setBackground(new java.awt.Color(24, 33, 43));
        min.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setText("-");
        min.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        HadingPanal.add(min);
        min.setBounds(970, 10, 40, 30);

        EmployeeHeading1.setBackground(new java.awt.Color(24, 33, 43));
        EmployeeHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        EmployeeHeading1.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeHeading1.setText("Employee");
        HadingPanal.add(EmployeeHeading1);
        EmployeeHeading1.setBounds(430, 0, 180, 50);

        jPanel1.setBackground(new java.awt.Color(24, 33, 43));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 33, 43), 1, true));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(24, 33, 43));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 33, 43), 1, true));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(24, 33, 43));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        jPanel7.setBackground(new java.awt.Color(234, 236, 238));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setBackground(new java.awt.Color(24, 33, 43));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill application");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));

        Billaplicationtext.setBackground(new java.awt.Color(234, 236, 238));
        Billaplicationtext.setLineWrap(true);
        Billaplicationtext.setRows(5);
        Billaplicationtext.setTabSize(4);
        Billaplicationtext.setWrapStyleWord(true);
        Billaplicationtext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        jScrollPane6.setViewportView(Billaplicationtext);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(234, 236, 238));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.setLayout(null);

        totalAmount.setBackground(new java.awt.Color(24, 33, 43));
        totalAmount.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        totalAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalAmountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                totalAmountMouseEntered(evt);
            }
        });
        jPanel8.add(totalAmount);
        totalAmount.setBounds(200, 350, 230, 38);

        Billno.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Billno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Billno.setText("Bill no");
        jPanel8.add(Billno);
        Billno.setBounds(10, 60, 190, 38);

        companyaddress.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        companyaddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyaddress.setText("Company address");
        jPanel8.add(companyaddress);
        companyaddress.setBounds(11, 170, 190, 38);

        companyname.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        companyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyname.setText("company name");
        jPanel8.add(companyname);
        companyname.setBounds(11, 112, 190, 38);

        WorkingBill.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        WorkingBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkingBill.setText("Total working bill");
        jPanel8.add(WorkingBill);
        WorkingBill.setBounds(11, 231, 190, 38);

        Advancepay.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Advancepay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Advancepay.setText("Avanced pay");
        jPanel8.add(Advancepay);
        Advancepay.setBounds(10, 290, 190, 38);

        AcountDetail.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AcountDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcountDetail.setText("Acount detaile");
        jPanel8.add(AcountDetail);
        AcountDetail.setBounds(10, 410, 190, 38);

        BillNoText.setBackground(new java.awt.Color(234, 236, 238));
        BillNoText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        BillNoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BillNoText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BillNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillNoTextActionPerformed(evt);
            }
        });
        jPanel8.add(BillNoText);
        BillNoText.setBounds(200, 60, 230, 36);

        AcountDetaileText.setBackground(new java.awt.Color(234, 236, 238));
        AcountDetaileText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AcountDetaileText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AcountDetaileText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AcountDetaileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcountDetaileTextActionPerformed(evt);
            }
        });
        jPanel8.add(AcountDetaileText);
        AcountDetaileText.setBounds(200, 410, 230, 40);

        CompanyNameText.setBackground(new java.awt.Color(234, 236, 238));
        CompanyNameText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CompanyNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyNameText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CompanyNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextActionPerformed(evt);
            }
        });
        jPanel8.add(CompanyNameText);
        CompanyNameText.setBounds(200, 110, 230, 40);

        CompanyAddressText.setBackground(new java.awt.Color(234, 236, 238));
        CompanyAddressText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CompanyAddressText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyAddressText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CompanyAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyAddressTextActionPerformed(evt);
            }
        });
        jPanel8.add(CompanyAddressText);
        CompanyAddressText.setBounds(200, 170, 230, 40);

        WorkingBillText.setBackground(new java.awt.Color(234, 236, 238));
        WorkingBillText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        WorkingBillText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WorkingBillText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        WorkingBillText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingBillTextActionPerformed(evt);
            }
        });
        jPanel8.add(WorkingBillText);
        WorkingBillText.setBounds(200, 230, 230, 40);

        AdvancePayText.setBackground(new java.awt.Color(234, 236, 238));
        AdvancePayText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AdvancePayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdvancePayText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdvancePayText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdvancePayTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdvancePayTextMouseExited(evt);
            }
        });
        AdvancePayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancePayTextActionPerformed(evt);
            }
        });
        jPanel8.add(AdvancePayText);
        AdvancePayText.setBounds(200, 290, 230, 40);

        BillSave.setBackground(new java.awt.Color(234, 236, 238));
        BillSave.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        BillSave.setText("Save");
        BillSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        BillSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BillSave.setFocusPainted(false);
        BillSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillSaveActionPerformed(evt);
            }
        });
        jPanel8.add(BillSave);
        BillSave.setBounds(180, 480, 150, 40);

        payableAmount1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        payableAmount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payableAmount1.setText("Total payable amount");
        jPanel8.add(payableAmount1);
        payableAmount1.setBounds(10, 350, 190, 38);

        jLabel3.setBackground(new java.awt.Color(24, 33, 43));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bill information");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        jPanel8.add(jLabel3);
        jLabel3.setBounds(11, 12, 424, 38);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bill", jPanel4);

        jPanel3.setBackground(new java.awt.Color(24, 33, 43));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        jPanel3.setLayout(null);

        QuotationSearchPanel1.setBackground(new java.awt.Color(234, 236, 238));
        QuotationSearchPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        ProductCatagoryOption.setBackground(new java.awt.Color(234, 236, 238));
        ProductCatagoryOption.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductCatagoryOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Civil Work", "Iron Work", "Wooden Work", "Steel Work", "Sanetary Work", "Plambing Work", "Electrical Work", "Landscap", "Others" }));
        ProductCatagoryOption.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ProductCatagoryOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductCatagoryOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductCatagoryOptionMouseClicked(evt);
            }
        });
        ProductCatagoryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCatagoryOptionActionPerformed(evt);
            }
        });

        CatagoryLabale.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        CatagoryLabale.setText("Select Catagory");

        QuotationProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Discription", "Catagory", "unit", "prise"
            }
        ));
        QuotationProductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuotationProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuotationProductTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(QuotationProductTable);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuotationSearchPanel1Layout = new javax.swing.GroupLayout(QuotationSearchPanel1);
        QuotationSearchPanel1.setLayout(QuotationSearchPanel1Layout);
        QuotationSearchPanel1Layout.setHorizontalGroup(
            QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuotationSearchPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(CatagoryLabale, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductCatagoryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuotationSearchPanel1Layout.setVerticalGroup(
            QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatagoryLabale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCatagoryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(QuotationSearchPanel1);
        QuotationSearchPanel1.setBounds(10, 10, 930, 270);

        jPanel5.setBackground(new java.awt.Color(234, 236, 238));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        QuotationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Discription", "Catagory", "Unit", "Quantity", "Unit Price", "total"
            }
        ));
        QuotationTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane4.setViewportView(QuotationTable);

        Save.setBackground(new java.awt.Color(234, 236, 238));
        Save.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Save.setText("Save");
        Save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.setFocusPainted(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        ProductDescriptionLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel2.setText("Quotation No");

        QuotationNo.setBackground(new java.awt.Color(234, 236, 238));
        QuotationNo.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        QuotationNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuotationNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QuotationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotationNoActionPerformed(evt);
            }
        });

        ProductDescriptionLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel4.setText("Company name");

        ReciverCompanyNameText.setBackground(new java.awt.Color(234, 236, 238));
        ReciverCompanyNameText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        ReciverCompanyNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReciverCompanyNameText.setText("Enter Reciver Company name");
        ReciverCompanyNameText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ReciverCompanyNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReciverCompanyNameTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReciverCompanyNameTextMouseEntered(evt);
            }
        });
        ReciverCompanyNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciverCompanyNameTextActionPerformed(evt);
            }
        });

        ProductDescriptionLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel3.setText("Address");

        RecivedrCompanyAddressText.setBackground(new java.awt.Color(234, 236, 238));
        RecivedrCompanyAddressText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        RecivedrCompanyAddressText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RecivedrCompanyAddressText.setText("Reciver company Address ");
        RecivedrCompanyAddressText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        RecivedrCompanyAddressText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecivedrCompanyAddressTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecivedrCompanyAddressTextMouseEntered(evt);
            }
        });
        RecivedrCompanyAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecivedrCompanyAddressTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuotationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ProductDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ReciverCompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProductDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RecivedrCompanyAddressText)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuotationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReciverCompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecivedrCompanyAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 290, 930, 260);

        jTabbedPane1.addTab("Quotation", jPanel3);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1060, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HadingPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HadingPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Unsaved data will be lost\nWant to exit?") == 0) {
            System.exit(0);
        }


    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setForeground(new java.awt.Color(128, 0, 0));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setForeground(new java.awt.Color(128, 128, 128));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_minMouseExited
    private boolean VarifyQuotation() {
        if (QuotationNo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty Quotation number");
            return false;
        } else if (ReciverCompanyNameText.getText().equals("Enter Reciver Company name")
                || ReciverCompanyNameText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty Company name");
            return false;
        } else if (RecivedrCompanyAddressText.getText().equals("Reciver company Address ")
                || RecivedrCompanyAddressText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty company address");
            return false;
        } else {
            return true;
        }

    }

    private void EmployeeLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Unsaved data will be lost\nWant to Logout?") == 0) {
            Login lin = new Login();
            lin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EmployeeLogoutMouseClicked

    private void EmployeeLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseEntered
        EmployeeLogout.setForeground(new java.awt.Color(128, 0, 0));
    }//GEN-LAST:event_EmployeeLogoutMouseEntered

    private void EmployeeLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseExited
        EmployeeLogout.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_EmployeeLogoutMouseExited

    private void RecivedrCompanyAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecivedrCompanyAddressTextActionPerformed

    private void RecivedrCompanyAddressTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextMouseEntered

    }//GEN-LAST:event_RecivedrCompanyAddressTextMouseEntered

    private void RecivedrCompanyAddressTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextMouseClicked
        RecivedrCompanyAddressText.setText(null);
    }//GEN-LAST:event_RecivedrCompanyAddressTextMouseClicked

    private void ReciverCompanyNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextActionPerformed

    }//GEN-LAST:event_ReciverCompanyNameTextActionPerformed

    private void ReciverCompanyNameTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextMouseEntered

    }//GEN-LAST:event_ReciverCompanyNameTextMouseEntered

    private void ReciverCompanyNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextMouseClicked
        ReciverCompanyNameText.setText(null);
    }//GEN-LAST:event_ReciverCompanyNameTextMouseClicked

    private void QuotationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuotationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuotationNoActionPerformed

    /*private void comLogo() {
    Connection con = DBConnection.getConnection();
    String quary = "SELECT * FROM `admin` WHERE `id`=1";
    
    try {
    Statement st = (Statement) con.createStatement();
    ResultSet rs = st.executeQuery(quary);
    if (rs.next()) {//now on 1st row
    
    byte[] img = rs.getBytes("Logo");
    Image imag=
    } else {
    JOptionPane.showMessageDialog(null, "No Data");
    }
    } catch (SQLException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }*/
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String Qno;
        String recivedComName;
        String RecivedComAdd;
        String MyAdd = null;
        String MyCompany = null;
        float total = 0;

        Connection con = DBConnection.getConnection();
        String quary = "SELECT * FROM `admin` WHERE `id`=1";

        if (VarifyQuotation()) {

            Qno = QuotationNo.getText();
            recivedComName = (String) ReciverCompanyNameText.getText();
            RecivedComAdd = (String) RecivedrCompanyAddressText.getText();
            
            Image image;

            Document document = new Document();
            try {
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(Qno + ".pdf"));
                document.open();
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(quary);
                if (rs.next()) {//now on 1st row

                    byte[] img = rs.getBytes("Logo");
                    MyCompany = rs.getString("CompanyName");
                    MyAdd = rs.getString("CompanyAddress");
                    image = Image.getInstance(img);
                    image.scaleAbsolute(150, 50);
                    document.add(image);
                }
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("\n"));
                Paragraph pr1 = new Paragraph();
                Paragraph pr2 = new Paragraph();
                Paragraph pr3 = new Paragraph();
                Paragraph pr4 = new Paragraph();
                Paragraph pr5 = new Paragraph();
                Paragraph pr6 = new Paragraph();
                Paragraph pr7 = new Paragraph();

                pr1.setFont(FontFactory.getFont(FontFactory.TIMES, 18, Font.BOLD));
                pr1.add(recivedComName);
                document.add(pr1);
                pr2.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr2.add(RecivedComAdd);
                document.add(pr2); // heading last
                
                document.add(new Paragraph("\n"));
                
                PdfPTable table = new PdfPTable(6); // 3 columns.
                table.setWidthPercentage(100); //Width 100%
                table.setSpacingBefore(10f); //Space before table
                //table.setSpacingAfter(10f); //Space after table

                //Set Column widths
                float[] columnWidths = {.5f, 2f, .5f, 1f, 1f, 1f};
                table.setWidths(columnWidths);

                PdfPCell cell1 = new PdfPCell(new Paragraph("sl\nno"));
                cell1.setBorderColor(BaseColor.BLACK);
                cell1.setPaddingLeft(10);
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell2 = new PdfPCell(new Paragraph("Description"));
                cell2.setBorderColor(BaseColor.BLACK);
                cell2.setPaddingLeft(10);
                cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell3 = new PdfPCell(new Paragraph("Unit"));
                cell3.setBorderColor(BaseColor.BLACK);
                cell3.setPaddingLeft(10);
                cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell4 = new PdfPCell(new Paragraph("Quantity"));
                cell4.setBorderColor(BaseColor.BLACK);
                cell4.setPaddingLeft(10);
                cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell4.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell5 = new PdfPCell(new Paragraph("Unit\nprice"));
                cell5.setBorderColor(BaseColor.BLACK);
                cell5.setPaddingLeft(10);
                cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell5.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell6 = new PdfPCell(new Paragraph("Total"));
                cell6.setBorderColor(BaseColor.BLACK);
                cell6.setPaddingLeft(10);
                cell6.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell6.setVerticalAlignment(Element.ALIGN_MIDDLE);

                table.addCell(cell1);
                table.addCell(cell2);
                table.addCell(cell3);
                table.addCell(cell4);
                table.addCell(cell5);
                table.addCell(cell6);

                DefaultTableModel model2 = (DefaultTableModel) QuotationTable.getModel();
                int n = QuotationTable.getRowCount();
                //model1.getValueAt(indexs[i], 0)
                for (int i = 0; i < n; i++) {
                    String ans1 = String.valueOf(i+1);
                    PdfPCell c1 = new PdfPCell(new Paragraph(ans1));
                    c1.setBorderColor(BaseColor.BLACK);
                    c1.setPaddingLeft(10);
                    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c1.setVerticalAlignment(Element.ALIGN_MIDDLE);

                    String ans2 = String.valueOf(model2.getValueAt(i, 1));
                    PdfPCell c2 = new PdfPCell(new Paragraph(ans2));
                    c2.setBorderColor(BaseColor.BLACK);
                    c2.setPaddingLeft(10);
                    c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c2.setVerticalAlignment(Element.ALIGN_MIDDLE);

                    String ans3 = String.valueOf(model2.getValueAt(i, 3));
                    PdfPCell c3 = new PdfPCell(new Paragraph(ans3));
                    c3.setBorderColor(BaseColor.BLACK);
                    c3.setPaddingLeft(10);
                    c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c3.setVerticalAlignment(Element.ALIGN_MIDDLE);

                    String ans4 = String.valueOf(model2.getValueAt(i, 4));
                    PdfPCell c4 = new PdfPCell(new Paragraph(ans4));
                    c4.setBorderColor(BaseColor.BLACK);
                    c4.setPaddingLeft(10);
                    c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c4.setVerticalAlignment(Element.ALIGN_MIDDLE);

                    String ans5 = String.valueOf(model2.getValueAt(i, 5));
                    PdfPCell c5 = new PdfPCell(new Paragraph(ans4));
                    c5.setBorderColor(BaseColor.BLACK);
                    c5.setPaddingLeft(10);
                    c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c5.setVerticalAlignment(Element.ALIGN_MIDDLE);

                    String ans6 = String.valueOf(model2.getValueAt(i, 6));
                    total+=Float.valueOf(ans6);
                    PdfPCell c6 = new PdfPCell(new Paragraph(ans6));
                    c6.setBorderColor(BaseColor.BLACK);
                    c6.setPaddingLeft(10);
                    c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                    c6.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    table.addCell(c1);
                    table.addCell(c2);
                    table.addCell(c3);
                    table.addCell(c4);
                    table.addCell(c5);
                    table.addCell(c6);
                }
                
                document.add(table);
                PdfPTable table1 = new PdfPTable(2); // 3 columns.
                table1.setWidthPercentage(100); //Width 100%
                
                
                //table.setSpacingBefore(10f); //Space before table
                table1.setSpacingAfter(10f); //Space after table
                PdfPCell nc = new PdfPCell(new Paragraph("Total"));
                    nc.setBorderColor(BaseColor.BLACK);
                    nc.setPaddingLeft(10);
                    nc.setHorizontalAlignment(Element.ALIGN_CENTER);
                    nc.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell nc1 = new PdfPCell(new Paragraph(String.valueOf(total)));
                    nc1.setBorderColor(BaseColor.BLACK);
                    nc1.setPaddingLeft(10);
                    nc1.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    nc1.setVerticalAlignment(Element.ALIGN_MIDDLE);
                table1.addCell(nc);
                table1.addCell(nc1);
                document.add(table1);
                
                
                int rtotal = (int) total;
                int gtotal = (10*rtotal)/100;
                int vat = (int) ((7.5*gtotal)/100);
                int exvat = rtotal+gtotal;
                int invat = rtotal+gtotal+vat;
                
                PdfPTable table2 = new PdfPTable(2); // 3 columns.
                table2.setWidthPercentage(100); //Width 100%
                
                
                table2.setSpacingBefore(10f); //Space before table
                table2.setSpacingAfter(10f); //Space after table
                PdfPCell t2c1 = new PdfPCell(new Paragraph("Discription"));
                    t2c1.setBorderColor(BaseColor.BLACK);
                    t2c1.setPaddingLeft(10);
                    t2c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2 = new PdfPCell(new Paragraph("total"));
                    t2c2.setBorderColor(BaseColor.BLACK);
                    t2c2.setPaddingLeft(10);
                    t2c2.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                PdfPCell t2c1_1 = new PdfPCell(new Paragraph("Estimated Cost"));
                    t2c1_1.setBorderColor(BaseColor.BLACK);
                    t2c1_1.setPaddingLeft(10);
                    t2c1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1_1.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2_1 = new PdfPCell(new Paragraph(String.valueOf(total)));
                    t2c2_1.setBorderColor(BaseColor.BLACK);
                    t2c2_1.setPaddingLeft(10);
                    t2c2_1.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2_1.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                PdfPCell t2c1_2 = new PdfPCell(new Paragraph("Designe and Supervision 10% of cost"));
                    t2c1_2.setBorderColor(BaseColor.BLACK);
                    t2c1_2.setPaddingLeft(10);
                    t2c1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1_2.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2_2 = new PdfPCell(new Paragraph(String.valueOf(gtotal)));
                    t2c2_2.setBorderColor(BaseColor.BLACK);
                    t2c2_2.setPaddingLeft(10);
                    t2c2_2.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2_2.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                    PdfPCell t2c1_3 = new PdfPCell(new Paragraph("7.5% vat"));
                    t2c1_3.setBorderColor(BaseColor.BLACK);
                    t2c1_3.setPaddingLeft(10);
                    t2c1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1_3.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2_3 = new PdfPCell(new Paragraph(String.valueOf(vat)));
                    t2c2_3.setBorderColor(BaseColor.BLACK);
                    t2c2_3.setPaddingLeft(10);
                    t2c2_3.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2_3.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                    PdfPCell t2c1_4 = new PdfPCell(new Paragraph("Vat Excludion budget"));
                    t2c1_4.setBorderColor(BaseColor.BLACK);
                    t2c1_4.setPaddingLeft(10);
                    t2c1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1_4.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2_4 = new PdfPCell(new Paragraph(String.valueOf(exvat)));
                    t2c2_4.setBorderColor(BaseColor.BLACK);
                    t2c2_4.setPaddingLeft(10);
                    t2c2_4.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2_4.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                    PdfPCell t2c1_5 = new PdfPCell(new Paragraph("Vat Including budget"));
                    t2c1_5.setBorderColor(BaseColor.BLACK);
                    t2c1_5.setPaddingLeft(10);
                    t2c1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
                    t2c1_5.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell t2c2_5 = new PdfPCell(new Paragraph(String.valueOf(invat)));
                    t2c2_5.setBorderColor(BaseColor.BLACK);
                    t2c2_5.setPaddingLeft(10);
                    t2c2_5.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    t2c2_5.setVerticalAlignment(Element.ALIGN_MIDDLE);
                table2.addCell(t2c1);
                table2.addCell(t2c2);
                table2.addCell(t2c1_1);
                table2.addCell(t2c2_1);
                table2.addCell(t2c1_2);
                table2.addCell(t2c2_2);
                table2.addCell(t2c1_3);
                table2.addCell(t2c2_3);
                table2.addCell(t2c1_4);
                table2.addCell(t2c2_4);
                table2.addCell(t2c1_5);
                table2.addCell(t2c2_5);
                
                document.add(table2);
                
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("\n"));
                pr3.setFont(FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
                pr3.add("Note : All are approximate quantity price which should be change as per actual quantity.");
                document.add(pr3);
                document.add(new Paragraph("\n"));
                pr4.setFont(FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
                pr4.add("(after completed the total Project. This is the quotation excluding Air Conditioning and thin\n"
                        + "quotition valid for only 21 dayes)");
                document.add(pr4);
                document.add(new Paragraph("\n"));

                pr5.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr5.add(MyCompany);
                document.add(pr5);
                pr6.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr6.add(MyAdd);
                document.add(pr6);
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("--------------"));

                pr7.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr7.add("Signature");
                document.add(pr7);

                document.close();
                JOptionPane.showMessageDialog(null, "Quotation successfully created");
            } catch (Exception ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TableModel model1 = QuotationProductTable.getModel();
        int indexs[] = QuotationProductTable.getSelectedRows();

        Object[] row = new Object[7];

        DefaultTableModel model2 = (DefaultTableModel) QuotationTable.getModel();

        for (int i = 0; i < indexs.length; i++) {
            row[0] = model1.getValueAt(indexs[i], 0);
            row[1] = model1.getValueAt(indexs[i], 1);
            row[2] = model1.getValueAt(indexs[i], 2);
            row[3] = model1.getValueAt(indexs[i], 3);

            row[4] = Quantity;
            row[5] = model1.getValueAt(indexs[i], 4);
            row[6] = (float) model1.getValueAt(indexs[i], 4) * Quantity;
            model2.addRow(row);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QuotationProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuotationProductTableMouseClicked
        TableModel model1 = QuotationProductTable.getModel();
        srow = QuotationProductTable.getSelectedRow();
        Quantity = Float.parseFloat(JOptionPane.showInputDialog("Enter product quantity"));
        tatalprice = (float) model1.getValueAt(srow, 4) * Quantity;

    }//GEN-LAST:event_QuotationProductTableMouseClicked

    private void ProductCatagoryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCatagoryOptionActionPerformed
        DefaultTableModel model = (DefaultTableModel) QuotationProductTable.getModel();
        model.setRowCount(0);
        ShowDataInproducttable();
    }//GEN-LAST:event_ProductCatagoryOptionActionPerformed

    private void ProductCatagoryOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductCatagoryOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductCatagoryOptionMouseClicked

    private void BillSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillSaveActionPerformed
        Connection con = DBConnection.getConnection();
        String quary = "SELECT * FROM `admin` WHERE `id`=1";
        String billNo;
        String compantname;
        String companyaddress;
        String totalbill;
        String advance;
        String amount;
        String accountno;
        String Application;
        String MyCompany = null;
        String MyAdd = null;

        if (VarifyBill()) {
            billNo = (String) BillNoText.getText();
            compantname = (String) CompanyNameText.getText();
            companyaddress = (String) CompanyAddressText.getText();
            totalbill = (String) WorkingBillText.getText();
            advance = (String) AdvancePayText.getText();
            amount = String.valueOf(Integer.valueOf(totalbill) - Integer.valueOf(advance));
            accountno = (String) AcountDetaileText.getText();
            Application = (String) Billaplicationtext.getText();
            System.out.println(billNo + "\n"
                    + compantname + "\n"
                    + companyaddress + "\n"
                    + totalbill + "\n"
                    + advance + "\n"
                    + amount + "\n"
                    + accountno);
            Image image;

            Document document = new Document();
            try {
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(billNo + ".pdf"));
                document.open();
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(quary);

                Paragraph pr1 = new Paragraph();
                Paragraph pr2 = new Paragraph();
                Paragraph pr3 = new Paragraph();
                Paragraph pr4 = new Paragraph();
                Paragraph pr5 = new Paragraph();
                Paragraph pr6 = new Paragraph();

                pr1.setFont(FontFactory.getFont(FontFactory.TIMES, 18, Font.BOLD));
                pr1.add(compantname);
                document.add(pr1);
                pr2.setFont(FontFactory.getFont(FontFactory.TIMES, 14));
                pr2.add(companyaddress);
                document.add(pr2); // heading last

                document.add(new Paragraph("\n"));
                document.add(new Paragraph("\n"));

                pr3.setFont(FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
                pr3.add(Application);
                document.add(pr3);

                document.add(new Paragraph("\n"));
                document.add(new Paragraph("\n"));

                PdfPTable table = new PdfPTable(2); // 3 columns.
                table.setWidthPercentage(100); //Width 100%
                table.setSpacingBefore(10f); //Space before table
                table.setSpacingAfter(10f); //Space after table

                //Set Column widths
                float[] columnWidths = {1f, 1f};
                table.setWidths(columnWidths);
                PdfPCell cell1 = new PdfPCell(new Paragraph("Total working bill"));
                cell1.setBorderColor(BaseColor.BLACK);
                cell1.setPaddingLeft(10);
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell1_2 = new PdfPCell(new Paragraph(totalbill));
                cell1_2.setBorderColor(BaseColor.BLACK);
                cell1_2.setPaddingLeft(10);
                cell1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1_2.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cel12 = new PdfPCell(new Paragraph("Avanced pay"));
                cel12.setBorderColor(BaseColor.BLACK);
                cel12.setPaddingLeft(10);
                cel12.setHorizontalAlignment(Element.ALIGN_CENTER);
                cel12.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cell2_2 = new PdfPCell(new Paragraph(advance));
                cell2_2.setBorderColor(BaseColor.BLACK);
                cell2_2.setPaddingLeft(10);
                cell2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell2_2.setVerticalAlignment(Element.ALIGN_MIDDLE);
                PdfPCell cel13 = new PdfPCell(new Paragraph("Due Amount"));
                cel13.setBorderColor(BaseColor.BLACK);
                cel13.setPaddingLeft(10);
                cel13.setHorizontalAlignment(Element.ALIGN_CENTER);
                cel13.setVerticalAlignment(Element.ALIGN_MIDDLE);

                PdfPCell cel3_2 = new PdfPCell(new Paragraph(amount));
                cel3_2.setBorderColor(BaseColor.BLACK);
                cel3_2.setPaddingLeft(10);
                cel3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cel3_2.setVerticalAlignment(Element.ALIGN_MIDDLE);
                table.addCell(cell1);
                table.addCell(cell1_2);
                table.addCell(cel12);
                table.addCell(cell2_2);
                table.addCell(cel13);
                table.addCell(cel3_2);
                document.add(table);

                document.add(new Paragraph("\n"));
                document.add(new Paragraph("\n"));

                
                pr4.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr4.add(MyCompany);
                document.add(pr4);
                pr5.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr5.add(MyAdd);
                document.add(pr5);
                document.add(new Paragraph("\n"));
                document.add(new Paragraph("--------------"));

                pr6.setFont(FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD));
                pr6.add("Signature");
                document.add(pr6);

                document.close();
                JOptionPane.showMessageDialog(null, "Bill successfully created");
            } catch (DocumentException | HeadlessException | IOException | SQLException ex) {
                Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
            }

            SetVarifyBillToNull();
        }
    }//GEN-LAST:event_BillSaveActionPerformed

    private void AdvancePayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancePayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdvancePayTextActionPerformed

    private void WorkingBillTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingBillTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkingBillTextActionPerformed

    private void CompanyAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyAddressTextActionPerformed

    private void CompanyNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextActionPerformed

    private void AcountDetaileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcountDetaileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcountDetaileTextActionPerformed

    private void BillNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillNoTextActionPerformed

    private void AdvancePayTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvancePayTextMouseExited

    }//GEN-LAST:event_AdvancePayTextMouseExited

    private void AdvancePayTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdvancePayTextMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AdvancePayTextMouseEntered

    private void totalAmountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalAmountMouseEntered


    }//GEN-LAST:event_totalAmountMouseEntered

    private void totalAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalAmountMouseClicked
        String amount = String.valueOf(Integer.valueOf(WorkingBillText.getText()) - Integer.valueOf(AdvancePayText.getText()));
        totalAmount.setText(amount);
    }//GEN-LAST:event_totalAmountMouseClicked
    private boolean VarifyBill() {
        if (BillNoText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty Bill number");
            return false;
        } else if (Billaplicationtext.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Add an application with bill");
            return false;
        } else if (CompanyNameText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty reciver company Name");
            return false;
        } else if (CompanyAddressText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty reciver company Address");
            return false;
        } else if (WorkingBillText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Working bill Empty");
            return false;
        } else if (AdvancePayText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty Advance Pay");
            return false;
        } else if (AcountDetaileText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Acount Detaile not found");
            return false;
        } else {
            return true;
        }

    }

    private void SetVarifyBillToNull() {
        BillNoText.setText("");
        Billaplicationtext.setText("");
        CompanyNameText.setText("");
        CompanyAddressText.setText("");
        WorkingBillText.setText("");
        AdvancePayText.setText("");
        AcountDetaileText.setText("");
        totalAmount.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcountDetail;
    private javax.swing.JTextField AcountDetaileText;
    private javax.swing.JTextField AdvancePayText;
    private javax.swing.JLabel Advancepay;
    private javax.swing.JTextField BillNoText;
    private javax.swing.JButton BillSave;
    private javax.swing.JTextArea Billaplicationtext;
    private javax.swing.JLabel Billno;
    private javax.swing.JLabel CatagoryLabale;
    private javax.swing.JTextField CompanyAddressText;
    private javax.swing.JTextField CompanyNameText;
    private javax.swing.JLabel EmployeeHeading1;
    private javax.swing.JLabel EmployeeLogout;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel HadingPanal;
    private javax.swing.JComboBox<String> ProductCatagoryOption;
    private javax.swing.JLabel ProductDescriptionLabel2;
    private javax.swing.JLabel ProductDescriptionLabel3;
    private javax.swing.JLabel ProductDescriptionLabel4;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JTextField QuotationNo;
    private javax.swing.JTable QuotationProductTable;
    private javax.swing.JPanel QuotationSearchPanel1;
    private javax.swing.JTable QuotationTable;
    private javax.swing.JTextField RecivedrCompanyAddressText;
    private javax.swing.JTextField ReciverCompanyNameText;
    private javax.swing.JButton Save;
    private javax.swing.JLabel WorkingBill;
    private javax.swing.JTextField WorkingBillText;
    private javax.swing.JLabel companyaddress;
    private javax.swing.JLabel companyname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel payableAmount1;
    private javax.swing.JLabel totalAmount;
    // End of variables declaration//GEN-END:variables
}
