/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quitation;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jahed
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HadingPanal = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        EmployeeLogout = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        EmployeeHeading1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewFile = new javax.swing.JTextArea();
        beowseFile = new javax.swing.JButton();
        PrintFile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        QuotationSearchPanel1 = new javax.swing.JPanel();
        ProductCatagoryOption = new javax.swing.JComboBox<>();
        CatagoryLabale = new javax.swing.JLabel();
        ProductSearchText = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        QuotationProductTable = new javax.swing.JTable();
        SendCompanyInfo1 = new javax.swing.JPanel();
        ProductDescriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuotationProductDiscription = new javax.swing.JTextArea();
        ProductDescriptionLabel1 = new javax.swing.JLabel();
        ProductQuantityText = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        QuotationTable = new javax.swing.JTable();
        Save = new javax.swing.JButton();
        CatagoryLabale1 = new javax.swing.JLabel();
        QuotationCatagory = new javax.swing.JComboBox<>();
        ProductDescriptionLabel2 = new javax.swing.JLabel();
        QuotationNo = new javax.swing.JTextField();
        ProductDescriptionLabel4 = new javax.swing.JLabel();
        ReciverCompanyNameText = new javax.swing.JTextField();
        ProductDescriptionLabel3 = new javax.swing.JLabel();
        RecivedrCompanyAddressText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Billaplicationtext = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Billno = new javax.swing.JLabel();
        companyaddress = new javax.swing.JLabel();
        companyname = new javax.swing.JLabel();
        WorkingBill = new javax.swing.JLabel();
        Advancepay = new javax.swing.JLabel();
        payableAmountOutput = new javax.swing.JLabel();
        AcountDetail = new javax.swing.JLabel();
        BillNoText = new javax.swing.JTextField();
        AcountDetaileText = new javax.swing.JTextField();
        CompanyNameText = new javax.swing.JTextField();
        CompanyAddressText = new javax.swing.JTextField();
        WorkingBillText = new javax.swing.JTextField();
        AdvancePayText = new javax.swing.JTextField();
        BillSave = new javax.swing.JButton();
        payableAmount1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HadingPanal.setBackground(new java.awt.Color(24, 33, 43));
        HadingPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 3, true));
        HadingPanal.setLayout(null);

        Q1.setBackground(new java.awt.Color(24, 33, 43));
        Q1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setText("Quotation");
        HadingPanal.add(Q1);
        Q1.setBounds(0, 0, 100, 30);

        Q2.setBackground(new java.awt.Color(24, 33, 43));
        Q2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2.setText("     Maker.");
        HadingPanal.add(Q2);
        Q2.setBounds(0, 16, 100, 30);

        EmployeeLogout.setBackground(new java.awt.Color(24, 33, 43));
        EmployeeLogout.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        EmployeeLogout.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeLogout.setText("Logout");
        EmployeeLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        EmployeeLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeLogoutMouseExited(evt);
            }
        });
        HadingPanal.add(EmployeeLogout);
        EmployeeLogout.setBounds(880, 10, 80, 30);

        Exit.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        HadingPanal.add(Exit);
        Exit.setBounds(1020, 10, 30, 30);

        min.setBackground(new java.awt.Color(24, 33, 43));
        min.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setText("-");
        min.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        HadingPanal.add(min);
        min.setBounds(970, 10, 40, 30);

        EmployeeHeading1.setBackground(new java.awt.Color(24, 33, 43));
        EmployeeHeading1.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        EmployeeHeading1.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeHeading1.setText("Employee");
        HadingPanal.add(EmployeeHeading1);
        EmployeeHeading1.setBounds(430, 0, 180, 50);

        jPanel1.setBackground(new java.awt.Color(24, 33, 43));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 33, 43), 1, true));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(24, 33, 43));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 33, 43), 1, true));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(24, 33, 43));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        jPanel6.setBackground(new java.awt.Color(234, 236, 238));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        ViewFile.setBackground(new java.awt.Color(234, 236, 238));
        ViewFile.setLineWrap(true);
        ViewFile.setRows(5);
        ViewFile.setTabSize(4);
        ViewFile.setWrapStyleWord(true);
        ViewFile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jScrollPane1.setViewportView(ViewFile);

        beowseFile.setBackground(new java.awt.Color(234, 236, 238));
        beowseFile.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        beowseFile.setText("Browse File");
        beowseFile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        PrintFile.setBackground(new java.awt.Color(234, 236, 238));
        PrintFile.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        PrintFile.setText("Print");
        PrintFile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beowseFile, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(PrintFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(beowseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(PrintFile, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View", jPanel2);

        jPanel3.setBackground(new java.awt.Color(24, 33, 43));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        jPanel3.setLayout(null);

        QuotationSearchPanel1.setBackground(new java.awt.Color(234, 236, 238));
        QuotationSearchPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        ProductCatagoryOption.setBackground(new java.awt.Color(234, 236, 238));
        ProductCatagoryOption.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductCatagoryOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Work", "Iron Work", "Wooden Work", "Steel Work", "Sanetary Work", "Plambing Work", "Electrical Work", "Landscap", "Others" }));
        ProductCatagoryOption.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ProductCatagoryOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductCatagoryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCatagoryOptionActionPerformed(evt);
            }
        });

        CatagoryLabale.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        CatagoryLabale.setText("Select Catagory");

        ProductSearchText.setBackground(new java.awt.Color(234, 236, 238));
        ProductSearchText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        ProductSearchText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProductSearchText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ProductSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductSearchTextActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(234, 236, 238));
        Search.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Search.setText("Search");
        Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.setFocusPainted(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        QuotationProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Discription", "unit", "prise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(QuotationProductTable);

        javax.swing.GroupLayout QuotationSearchPanel1Layout = new javax.swing.GroupLayout(QuotationSearchPanel1);
        QuotationSearchPanel1.setLayout(QuotationSearchPanel1Layout);
        QuotationSearchPanel1Layout.setHorizontalGroup(
            QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                .addGroup(QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(CatagoryLabale, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ProductCatagoryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ProductSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        QuotationSearchPanel1Layout.setVerticalGroup(
            QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuotationSearchPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CatagoryLabale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductCatagoryOption, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(QuotationSearchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );

        jPanel3.add(QuotationSearchPanel1);
        QuotationSearchPanel1.setBounds(10, 10, 430, 290);

        SendCompanyInfo1.setBackground(new java.awt.Color(234, 236, 238));
        SendCompanyInfo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        SendCompanyInfo1.setLayout(null);

        ProductDescriptionLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel.setText("Product Quantity");
        SendCompanyInfo1.add(ProductDescriptionLabel);
        ProductDescriptionLabel.setBounds(10, 120, 170, 30);

        QuotationProductDiscription.setBackground(new java.awt.Color(234, 236, 238));
        QuotationProductDiscription.setColumns(20);
        QuotationProductDiscription.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        QuotationProductDiscription.setLineWrap(true);
        QuotationProductDiscription.setRows(5);
        QuotationProductDiscription.setAutoscrolls(false);
        QuotationProductDiscription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane2.setViewportView(QuotationProductDiscription);

        SendCompanyInfo1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 10, 230, 90);

        ProductDescriptionLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel1.setText("Product discription");
        SendCompanyInfo1.add(ProductDescriptionLabel1);
        ProductDescriptionLabel1.setBounds(10, 40, 170, 40);

        ProductQuantityText.setBackground(new java.awt.Color(234, 236, 238));
        ProductQuantityText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        ProductQuantityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProductQuantityText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ProductQuantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductQuantityTextActionPerformed(evt);
            }
        });
        SendCompanyInfo1.add(ProductQuantityText);
        ProductQuantityText.setBounds(190, 120, 170, 30);

        Add.setBackground(new java.awt.Color(234, 236, 238));
        Add.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Add.setText("Add");
        Add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.setFocusPainted(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        SendCompanyInfo1.add(Add);
        Add.setBounds(230, 180, 100, 30);

        Delete.setBackground(new java.awt.Color(234, 236, 238));
        Delete.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.setFocusPainted(false);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        SendCompanyInfo1.add(Delete);
        Delete.setBounds(100, 180, 110, 30);

        jPanel3.add(SendCompanyInfo1);
        SendCompanyInfo1.setBounds(10, 310, 430, 240);

        jPanel5.setBackground(new java.awt.Color(234, 236, 238));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        QuotationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl.no", "Discription", "Unit", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(QuotationTable);

        Save.setBackground(new java.awt.Color(234, 236, 238));
        Save.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Save.setText("Save");
        Save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.setFocusPainted(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        CatagoryLabale1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        CatagoryLabale1.setText("Select Catagory");

        QuotationCatagory.setBackground(new java.awt.Color(234, 236, 238));
        QuotationCatagory.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        QuotationCatagory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QuotationCatagory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuotationCatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotationCatagoryActionPerformed(evt);
            }
        });

        ProductDescriptionLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel2.setText("Quotation No");

        QuotationNo.setBackground(new java.awt.Color(234, 236, 238));
        QuotationNo.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        QuotationNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuotationNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QuotationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotationNoActionPerformed(evt);
            }
        });

        ProductDescriptionLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel4.setText("Company name");

        ReciverCompanyNameText.setBackground(new java.awt.Color(234, 236, 238));
        ReciverCompanyNameText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        ReciverCompanyNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReciverCompanyNameText.setText("Enter Reciver Company name");
        ReciverCompanyNameText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ReciverCompanyNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReciverCompanyNameTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReciverCompanyNameTextMouseEntered(evt);
            }
        });
        ReciverCompanyNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciverCompanyNameTextActionPerformed(evt);
            }
        });

        ProductDescriptionLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        ProductDescriptionLabel3.setText("Address");

        RecivedrCompanyAddressText.setBackground(new java.awt.Color(234, 236, 238));
        RecivedrCompanyAddressText.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        RecivedrCompanyAddressText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RecivedrCompanyAddressText.setText("Reciver company Address ");
        RecivedrCompanyAddressText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        RecivedrCompanyAddressText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecivedrCompanyAddressTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RecivedrCompanyAddressTextMouseEntered(evt);
            }
        });
        RecivedrCompanyAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecivedrCompanyAddressTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(ProductDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CatagoryLabale1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuotationCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecivedrCompanyAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuotationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReciverCompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuotationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReciverCompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecivedrCompanyAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatagoryLabale1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuotationCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(450, 10, 500, 540);

        jTabbedPane1.addTab("Quotation", jPanel3);

        jPanel4.setBackground(new java.awt.Color(24, 33, 43));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));

        jPanel7.setBackground(new java.awt.Color(234, 236, 238));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setBackground(new java.awt.Color(24, 33, 43));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill application");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));

        Billaplicationtext.setBackground(new java.awt.Color(234, 236, 238));
        Billaplicationtext.setLineWrap(true);
        Billaplicationtext.setRows(5);
        Billaplicationtext.setTabSize(4);
        Billaplicationtext.setWrapStyleWord(true);
        Billaplicationtext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        jScrollPane6.setViewportView(Billaplicationtext);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(234, 236, 238));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(24, 33, 43));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bill information");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        jPanel8.add(jLabel2);
        jLabel2.setBounds(11, 12, 424, 38);

        Billno.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Billno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Billno.setText("Bill no");
        jPanel8.add(Billno);
        Billno.setBounds(10, 60, 190, 38);

        companyaddress.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        companyaddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyaddress.setText("Company address");
        jPanel8.add(companyaddress);
        companyaddress.setBounds(11, 170, 190, 38);

        companyname.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        companyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyname.setText("company name");
        jPanel8.add(companyname);
        companyname.setBounds(11, 112, 190, 38);

        WorkingBill.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        WorkingBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkingBill.setText("Total working bill");
        jPanel8.add(WorkingBill);
        WorkingBill.setBounds(11, 231, 190, 38);

        Advancepay.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Advancepay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Advancepay.setText("Avanced pay");
        jPanel8.add(Advancepay);
        Advancepay.setBounds(10, 290, 190, 38);

        payableAmountOutput.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        payableAmountOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payableAmountOutput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 2, true));
        jPanel8.add(payableAmountOutput);
        payableAmountOutput.setBounds(200, 350, 230, 38);

        AcountDetail.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AcountDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AcountDetail.setText("Acount detaile");
        jPanel8.add(AcountDetail);
        AcountDetail.setBounds(10, 410, 190, 38);

        BillNoText.setBackground(new java.awt.Color(234, 236, 238));
        BillNoText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        BillNoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BillNoText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BillNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillNoTextActionPerformed(evt);
            }
        });
        jPanel8.add(BillNoText);
        BillNoText.setBounds(200, 60, 230, 36);

        AcountDetaileText.setBackground(new java.awt.Color(234, 236, 238));
        AcountDetaileText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AcountDetaileText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AcountDetaileText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AcountDetaileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcountDetaileTextActionPerformed(evt);
            }
        });
        jPanel8.add(AcountDetaileText);
        AcountDetaileText.setBounds(200, 410, 230, 40);

        CompanyNameText.setBackground(new java.awt.Color(234, 236, 238));
        CompanyNameText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CompanyNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyNameText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CompanyNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyNameTextActionPerformed(evt);
            }
        });
        jPanel8.add(CompanyNameText);
        CompanyNameText.setBounds(200, 110, 230, 40);

        CompanyAddressText.setBackground(new java.awt.Color(234, 236, 238));
        CompanyAddressText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        CompanyAddressText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CompanyAddressText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CompanyAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyAddressTextActionPerformed(evt);
            }
        });
        jPanel8.add(CompanyAddressText);
        CompanyAddressText.setBounds(200, 170, 230, 40);

        WorkingBillText.setBackground(new java.awt.Color(234, 236, 238));
        WorkingBillText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        WorkingBillText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WorkingBillText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        WorkingBillText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingBillTextActionPerformed(evt);
            }
        });
        jPanel8.add(WorkingBillText);
        WorkingBillText.setBounds(200, 230, 230, 40);

        AdvancePayText.setBackground(new java.awt.Color(234, 236, 238));
        AdvancePayText.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        AdvancePayText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdvancePayText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdvancePayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvancePayTextActionPerformed(evt);
            }
        });
        jPanel8.add(AdvancePayText);
        AdvancePayText.setBounds(200, 290, 230, 40);

        BillSave.setBackground(new java.awt.Color(234, 236, 238));
        BillSave.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        BillSave.setText("Save");
        BillSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        BillSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BillSave.setFocusPainted(false);
        BillSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillSaveActionPerformed(evt);
            }
        });
        jPanel8.add(BillSave);
        BillSave.setBounds(180, 480, 150, 40);

        payableAmount1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        payableAmount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payableAmount1.setText("Total payable amount");
        jPanel8.add(payableAmount1);
        payableAmount1.setBounds(10, 350, 190, 38);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bill", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1060, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HadingPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HadingPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Unsaved data will be lost\nWant to exit?")==0){
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setForeground(new java.awt.Color(128, 0, 0));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ExitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        min.setForeground(new java.awt.Color(128, 128, 128));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        min.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_minMouseExited

    private void ProductCatagoryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCatagoryOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductCatagoryOptionActionPerformed

    private void ProductSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductSearchTextActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        ProductSearchText.setText(null);
    }//GEN-LAST:event_SearchActionPerformed

    private void ProductQuantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductQuantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductQuantityTextActionPerformed
    private void setProductNull() {
        QuotationProductDiscription.setText(null);
        ProductQuantityText.setText(null);
    }
    private boolean VarifyAddProbuctData(){
        if(QuotationProductDiscription.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Select Product from avobe product list");
            return false;
        }
        else if(ProductQuantityText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Add product quantity");
            return false;
        }
        return true;
    }
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(VarifyAddProbuctData()){
            JOptionPane.showMessageDialog(null, "Product added to quotation");
            setProductNull();
        }
        
    }//GEN-LAST:event_AddActionPerformed
    private boolean VarifydeleteProbuctData(){
        if(QuotationProductDiscription.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Select Product from Quotation");
            return false;
        }
       
        return true;
    }
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(VarifydeleteProbuctData()){
            if(JOptionPane.showConfirmDialog(null, "Want to delete product from quotation?")==0){
                 setProductNull();
                 JOptionPane.showMessageDialog(null, "Product deleted");
            }
            
           
        }
    }//GEN-LAST:event_DeleteActionPerformed
    private boolean VarifyQuotation(){
        if(QuotationNo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Quotation number");
            return false;
        }
            
        else if(ReciverCompanyNameText.getText().equals("Enter Reciver Company name")
                ||ReciverCompanyNameText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Company name");
            return false;
        }
            
        else if(RecivedrCompanyAddressText.getText().equals("Reciver company Address ")
                ||RecivedrCompanyAddressText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty company address");
            return false;
        }
            
        else 
            return true;
        
    }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        
        if(VarifyQuotation()){
            JOptionPane.showMessageDialog(null, "Quotation successfully created");
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void QuotationCatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuotationCatagoryActionPerformed
        
    }//GEN-LAST:event_QuotationCatagoryActionPerformed

    private void RecivedrCompanyAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecivedrCompanyAddressTextActionPerformed

    private void QuotationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuotationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuotationNoActionPerformed

    private void ReciverCompanyNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextActionPerformed
        
    }//GEN-LAST:event_ReciverCompanyNameTextActionPerformed

    private void RecivedrCompanyAddressTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextMouseEntered
        
    }//GEN-LAST:event_RecivedrCompanyAddressTextMouseEntered

    private void ReciverCompanyNameTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextMouseEntered
        
    }//GEN-LAST:event_ReciverCompanyNameTextMouseEntered

    private void ReciverCompanyNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReciverCompanyNameTextMouseClicked
        ReciverCompanyNameText.setText(null);
    }//GEN-LAST:event_ReciverCompanyNameTextMouseClicked

    private void RecivedrCompanyAddressTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecivedrCompanyAddressTextMouseClicked
        RecivedrCompanyAddressText.setText(null);
    }//GEN-LAST:event_RecivedrCompanyAddressTextMouseClicked

    private void EmployeeLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Unsaved data will be lost\nWant to Logout?")==0){
            Login lin = new Login();
            lin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EmployeeLogoutMouseClicked

    private void EmployeeLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseEntered
        EmployeeLogout.setForeground(new java.awt.Color(128, 0, 0));
    }//GEN-LAST:event_EmployeeLogoutMouseEntered

    private void EmployeeLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLogoutMouseExited
        EmployeeLogout.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_EmployeeLogoutMouseExited

    private void BillNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillNoTextActionPerformed

    private void AcountDetaileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcountDetaileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcountDetaileTextActionPerformed

    private void CompanyNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyNameTextActionPerformed

    private void CompanyAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyAddressTextActionPerformed

    private void WorkingBillTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingBillTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkingBillTextActionPerformed

    private void AdvancePayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvancePayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdvancePayTextActionPerformed
    private boolean VarifyBill(){
        if(BillNoText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Bill number");
            return false;
        }
            
        else if(Billaplicationtext.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Add an application with bill");
            return false;
        }
            
        else if(CompanyNameText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty reciver company Name");
            return false;
        }
        else if(CompanyAddressText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty reciver company Address");
            return false;
        }  
        else if(WorkingBillText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Working bill Empty");
            return false;
        }  
        else if(AdvancePayText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Advance Pay");
            return false;
        }  
        else if(AcountDetaileText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Acount Detaile not found");
            return false;
        }  
         
        
        else 
            return true;
        
    }
    private void SetVarifyBillToNull(){
        BillNoText.setText("");
        Billaplicationtext.setText("");
        CompanyNameText.setText("");
        CompanyAddressText.setText("");
        WorkingBillText.setText("");
        AdvancePayText.setText("");
        AcountDetaileText.setText("");
        payableAmountOutput.setText("");
        
    }
    private void BillSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillSaveActionPerformed
        if(VarifyBill()){
            SetVarifyBillToNull();
        }
    }//GEN-LAST:event_BillSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcountDetail;
    private javax.swing.JTextField AcountDetaileText;
    private javax.swing.JButton Add;
    private javax.swing.JTextField AdvancePayText;
    private javax.swing.JLabel Advancepay;
    private javax.swing.JTextField BillNoText;
    private javax.swing.JButton BillSave;
    private javax.swing.JTextArea Billaplicationtext;
    private javax.swing.JLabel Billno;
    private javax.swing.JLabel CatagoryLabale;
    private javax.swing.JLabel CatagoryLabale1;
    private javax.swing.JTextField CompanyAddressText;
    private javax.swing.JTextField CompanyNameText;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel EmployeeHeading1;
    private javax.swing.JLabel EmployeeLogout;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel HadingPanal;
    private javax.swing.JButton PrintFile;
    private javax.swing.JComboBox<String> ProductCatagoryOption;
    private javax.swing.JLabel ProductDescriptionLabel;
    private javax.swing.JLabel ProductDescriptionLabel1;
    private javax.swing.JLabel ProductDescriptionLabel2;
    private javax.swing.JLabel ProductDescriptionLabel3;
    private javax.swing.JLabel ProductDescriptionLabel4;
    private javax.swing.JTextField ProductQuantityText;
    private javax.swing.JTextField ProductSearchText;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JComboBox<String> QuotationCatagory;
    private javax.swing.JTextField QuotationNo;
    private javax.swing.JTextArea QuotationProductDiscription;
    private javax.swing.JTable QuotationProductTable;
    private javax.swing.JPanel QuotationSearchPanel1;
    private javax.swing.JTable QuotationTable;
    private javax.swing.JTextField RecivedrCompanyAddressText;
    private javax.swing.JTextField ReciverCompanyNameText;
    private javax.swing.JButton Save;
    private javax.swing.JButton Search;
    private javax.swing.JPanel SendCompanyInfo1;
    private javax.swing.JTextArea ViewFile;
    private javax.swing.JLabel WorkingBill;
    private javax.swing.JTextField WorkingBillText;
    private javax.swing.JButton beowseFile;
    private javax.swing.JLabel companyaddress;
    private javax.swing.JLabel companyname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel payableAmount1;
    private javax.swing.JLabel payableAmountOutput;
    // End of variables declaration//GEN-END:variables
}
