/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quitation;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jahed
 */
public class WelComeForm extends javax.swing.JFrame {

    /**
     * Creates new form WelComeForm
     */
    public WelComeForm() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Stat2 = new javax.swing.JLabel();
        WelcomeExit = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(24, 33, 43));
        jPanel1.setLayout(null);

        Q1.setBackground(new java.awt.Color(24, 33, 43));
        Q1.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setText("Quotation");
        jPanel1.add(Q1);
        Q1.setBounds(0, 80, 310, 50);

        Q2.setBackground(new java.awt.Color(24, 33, 43));
        Q2.setFont(new java.awt.Font("Comic Sans MS", 2, 36)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2.setText("     Maker.");
        jPanel1.add(Q2);
        Q2.setBounds(0, 130, 310, 30);

        Stat2.setBackground(new java.awt.Color(24, 33, 43));
        Stat2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Stat2.setForeground(new java.awt.Color(255, 255, 255));
        Stat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stat2.setText("click cancel for exit");
        jPanel1.add(Stat2);
        Stat2.setBounds(0, 300, 310, 40);

        WelcomeExit.setBackground(new java.awt.Color(24, 33, 43));
        WelcomeExit.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        WelcomeExit.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeExit.setText("Cancel");
        WelcomeExit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        WelcomeExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        WelcomeExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WelcomeExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WelcomeExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WelcomeExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WelcomeExitMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                WelcomeExitMouseReleased(evt);
            }
        });
        jPanel1.add(WelcomeExit);
        WelcomeExit.setBounds(40, 360, 80, 40);

        Next.setBackground(new java.awt.Color(24, 33, 43));
        Next.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 255, 255));
        Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Next.setText("Next");
        Next.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 53, 63), 1, true));
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextMouseExited(evt);
            }
        });
        jPanel1.add(Next);
        Next.setBounds(190, 360, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WelcomeExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeExitMouseEntered
        WelcomeExit.setForeground(new java.awt.Color(128, 0, 0));
    }//GEN-LAST:event_WelcomeExitMouseEntered

    private void WelcomeExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeExitMouseExited
        WelcomeExit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_WelcomeExitMouseExited

    private void WelcomeExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeExitMouseReleased

    }//GEN-LAST:event_WelcomeExitMouseReleased

    private void WelcomeExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_WelcomeExitMouseClicked

    private void NextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseEntered
        Next.setForeground(new java.awt.Color(0, 128, 128));
    }//GEN-LAST:event_NextMouseEntered

    private void NextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseExited
        Next.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_NextMouseExited

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked

        String quary = "SELECT * FROM `admin` WHERE `id`=1";

        Connection con = DBConnection.getConnection();

        try {
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(quary);
            while (rs.next()) {
                String user = rs.getString("UserName");
                String pass = rs.getString("Password");
                if (user.equals("admin") && pass.equals("admin")) {
                    CreateProfile cp = new CreateProfile();
                    cp.setVisible(true);
                    this.dispose();
                } else {
                    Login lin = new Login();
                    lin.setVisible(true);
                    this.dispose();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(WelComeForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_NextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        new WelComeForm();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelComeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelComeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelComeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelComeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelComeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Stat2;
    private javax.swing.JLabel WelcomeExit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
